### ISSUE TITLE
Can't escape characters in cmd

### ISSUE THREAD

**Issue by stevengill** [polotek/procstreams#7]
This seems like a bug to me, but there may be a better way to do this.

Say I want to replicate the following command using procstreams

`sw_vers | awk '{print $2}'`

This doesn't work.

`p("sw_vers").pipe("awk '{print $2}'")`

It seems like it fails because it doesn't escape the single quote properly.

I tested this theory by doing two tests

`p("sw_vers").pipe("grep ProductVersion")`

and

`p("sw_vers").pipe("grep 'ProductVersion'")`

The top one without single quotes passes. The bottom one with single quotes failed. They both work in bash.

**Comment by polotek** [comment]
This is a bug. Thanks.

**Comment by polotek** [comment]
Hey, I pushed a branch with a more robust args parser. It uses a little grammar compiled by peg.js. Can you test it out and let me know what you think? Keep in mind this is running off master which has some other backwards incompatible changes in it. Doing a new release soon.

https://github.com/polotek/procstreams/tree/cmd-parser

**Comment by zfogg** [comment]
This bug persists, and it's kind of making procstreams unusable for me. I can't seem to make use of awk at all in the way that I need.

**Comment by polotek** [comment]
Sorry I've been neglecting this for a bit. I've got a couple of branches almost ready to go. Changes coming soon.
